artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  local_data_file: data/raw/WA_Fn-UseC_-Telco-Customer-Churn.csv
  train_data_file: artifacts/data_ingestion/train.csv
  test_data_file: artifacts/data_ingestion/test.csv

data_validation:
  root_dir: artifacts/data_validation
  validation_status_file: artifacts/data_validation/status.txt
  train_data_file: artifacts/data_ingestion/train.csv
  test_data_file: artifacts/data_ingestion/test.csv

data_transformation:
  root_dir: artifacts/data_transformation
  train_data_file: artifacts/data_ingestion/train.csv
  test_data_file: artifacts/data_ingestion/test.csv
  transformed_train_file: artifacts/data_transformation/train.csv
  transformed_test_file: artifacts/data_transformation/test.csv
  preprocessor_file: artifacts/data_transformation/preprocessor.pkl

model_training:
  root_dir: artifacts/model_training
  train_data_file: artifacts/data_transformation/train.csv
  test_data_file: artifacts/data_transformation/test.csv
  model_file: artifacts/model_training/model.pkl

model_evaluation:
  root_dir: artifacts/model_evaluation
  model_file: artifacts/model_training/model.pkl
  test_data_file: artifacts/data_transformation/test.csv
  evaluation_file: artifacts/model_evaluation/metrics.json

model_selection:
  root_dir: artifacts/model_selection
  model_file: artifacts/model_training/model.pkl
  evaluation_file: artifacts/model_evaluation/metrics.json
  selected_model_file: artifacts/model_selection/selected_model.pkl
  selection_file: artifacts/model_selection/selection.json
